#!/bin/bash

if [ ! -d ~/screenshots/ ]; then
  mkdir ~/screenshots/
fi

DATE=$(date +%Y-%m-%d-%T).png
SCREEN_PATH=~/screenshots/${DATE}

scrot $SCREEN_PATH

# Send notification
dunstify $DATE -I $SCREEN_PATH

# Add image to clipboard
xclip -se c -t image/png -i $SCREEN_PATH

